### ISSUE TITLE
Implement using tcp-ip

### ISSUE THREAD

**Issue by santoshphilip** [pyenergyplus/zeppy#5]
Now we have an ipc version.
do it in tcp=ip

as a next step bridge then network gap

**Comment by orcunkoraliseri** [comment]
Hello, 

I am using zeppy with Windows 10. I have encountered 
`zmq.error.ZMQError: Protocol not supported` problem.

I found a link which talk about ipc protocol on Windows 10.
https://github.com/jina-ai/clip-as-service/issues/39

How can i solve this problem? 

Thank you for your great effort with eppy.

**Comment by santoshphilip** [comment]
@orcunkoraliseri , I am travelling now with bad connectivity.
Back early next week. I'll take a closer look once I am back.

I think this is the issue.
zeppy is using `ipc` protocol. This works only on unix
zeppy needs to be upgraded to use `tcp-ip` protocol that works on windows

My recollection is that it is an easy upgrade (maybe)
I am glad you are trying to use it. Gives me motivation to upgrade it :-)

**Comment by orcunkoraliseri** [comment]
@santoshphilip, I'm glad the problem was easy. Unfortunately, I'm a Windows user, but I think I should also start working with Linux now.

I am using Eppy and its side libraries. You are doing a great job.

Thank you. I'll be waiting for the upgrade.

**Comment by orcunkoraliseri** [comment]
Any progress on the update? If there's anything I can help with, I'd love to hear it.

**Comment by santoshphilip** [comment]
I am back from my travels.
Time to start looking at it. Thanks for the reminder.

I will look at it with an eye to having you help. It often takes longer to collaborate, but the results are much better.

Give me a few days to get back into the code again.

**Comment by santoshphilip** [comment]
I am running into a bunch of issues running E+ (Did not have them before)
This is going to take linger than I anticipated.

**Comment by orcunkoraliseri** [comment]
I can understand that it may take longer than expected. I think that happens most of the time. I can wait until you complete it. Thank you so much.

**Comment by santoshphilip** [comment]
You are welcome to keep reminding me :-)

**Comment by santoshphilip** [comment]
fixed issue #5

:Problem: need a TCP version of ppipes.py
:Solution: ptcp is the TCP version of ppipes

**Comment by santoshphilip** [comment]
@orcunkoraliseri , the coding is done. I need to update the user documentation so that you get a sense of how to try it out

**Comment by santoshphilip** [comment]
@orcunkoraliseri I made a new release which works with TCP and has updated user documentation to match. 
Can you test it and confirm that things work.

I am not sure you are seeing these messages once the issue was closed.
I am reopening the issue

**Comment by orcunkoraliseri** [comment]
Thank you again for your effort @santoshphilip. Completing the code made me very happy. You are giving great support to my doctoral study.

What you write comes to me by mail. I didn't see it, so I couldn't answer. You don't need to open the issue again.

Due to the project, I am working on, I have to travel to different cities. I'm away from my computer right now. Can you give me a few days for testing? I'll try it as soon as I get to my computer. I can't wait to try it.

**Comment by santoshphilip** [comment]
not a problem. Get to it whenever you can.

I am curious about how zeppy helps in your doctoral work. 
I might have to stop considering zeppy as experimental and treat it as production code
(means more robust testing and clearer docstrings and user documentation)

**Comment by orcunkoraliseri** [comment]
I think I can easily explain this question. During my Ph.D., I am working on urban building energy modeling (UBEM). I'm considering using Zeppy for consecutive building energy simulations at a neighborhood scale. I need to simulate different buildings consecutively, with different numbers of residential units. 

Before, I used both eppy and geometry for my master's thesis. I needed to simulate a single thermal zone with different parameters. Fortunately, thanks to eppy, I was able to do this easily. However, simulating more than one residential unit in a building compared to a single zone becomes a more complex and time-consuming problem. 

If you want to get a more detailed understanding, I am sharing a publication that I derived from my master's thesis and a publication that I published during my doctoral thesis. 

I hope I was able to explain. Thank you very much for your hard work.

Publication from master thesis: 
-https://www.researchgate.net/publication/361137764_The_Impacts_of_Early_Architectural_Design_Decisions_on_Building_Performance


Publication during Ph.D.: 
- https://www.researchgate.net/publication/341617360_An_Algorithm_for_Efficient_Urban_Building_Energy_Modeling_and_Simulation

**Comment by orcunkoraliseri** [comment]
The problem has solved. It works on windows 10 pc. Thank you for your effort @santoshphilip

**Comment by santoshphilip** [comment]
I was thinking about this. Zeppy is overkill for most projects. Usually `runIDFs()` from eppy is good enough.
How many runs simulations would you be doing ?

- 1000, 10,000 or 100,000 or is it in millions ?
- How many computers are you using     
    - One computer, 5-10 computers, 100 computers or more    
    - are they on one network or on many separate networks

As the numbers get larger, zeppy starts to become useful.
Of course, not all of this has been coded, but I would find it interesting to so.

Again, if `runIDFs()` is good enough, you should use that.

**Comment by santoshphilip** [comment]
edited previous post for better formatting

**Comment by orcunkoraliseri** [comment]
I need to write a little bit longer to accurately describe what I'm trying to do. Technical details on zeppy are discussed here. So can I take your e-mail and write to you directly in order not to go into unnecessary details under this issue of zeppy? If you want, I would like to consult zeppy and eppy about technical issues in the process. Maybe I can contribute also to zeppy process by giving you an idea. I think the potential of zeppy is huge.

**Comment by santoshphilip** [comment]
@orcunkoraliseri I have sent an email to your dot edu address. Hit reply to confirm that you got it
